# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump - SemVer bumping made easy!"
  homepage "https://github.com/broothie/bump"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/broothie/bump/releases/download/0.0.5/bump_0.0.5_darwin_amd64.tar.gz"
    sha256 "7dbd9922a623f85f3b2fd30d0e48f70540e657c0539925b7718f6be110cca66f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/broothie/bump/releases/download/0.0.5/bump_0.0.5_linux_amd64.tar.gz"
      sha256 "ad6cf148920efaf1fe2e88a87a814405ab56090375e9ce02befd57a72d5621e4"
    end
  end

  def install
    bin.install "bump"
  end
end
