# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump - SemVer bumping made easy!"
  homepage "https://github.com/broothie/bump"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/broothie/bump/releases/download/0.0.4/bump_0.0.4_darwin_amd64.tar.gz"
    sha256 "0c960083fb6a68054cb61d26cc94810d8a72a6ebe3620d2aeb22cdc9b88a674d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/broothie/bump/releases/download/0.0.4/bump_0.0.4_linux_amd64.tar.gz"
      sha256 "622b65d1494fb76820c41562c5ae67baa3a420e35e4df46bc336471b4cc5e4eb"
    end
  end

  def install
    bin.install "bump"
  end
end
